<a href="https://colab.research.google.com/github/SarahAdmin/My-Python-Projects/blob/main/my-project-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
class Car:
  def __init__(self, make, model, colour, year):
    self.make = make
    self.model = model
    self.colour = colour
    self.year = year

  def MyCar(self):
    print('Make:   '+self.make)
    print('Model:   '+self.model)
    print('Colour:  '+self.colour)
    print('Year:  '+self.year)


p1 = Car('Toyota','Yaris','White','2024')

p1.MyCar()

Make:   Toyota
Model:   Yaris
Colour:  White
Year:  2024


In [3]:
import numpy as np
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
def LeapYears(year):
  return year % 4 == 0
print(LeapYears(1980))
print(LeapYears(1996))
print(LeapYears(1994))
print(LeapYears(1995))
print(LeapYears(2025))
print(LeapYears(2008))


True
True
False
False
False
True
